// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.Action EditAction;
    
    private Gtk.Action ViewAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action openAction;
    
    private Gtk.Action saveAction;
    
    private Gtk.Action saveAsAction;
    
    private Gtk.Action OpenAction;
    
    private Gtk.Action SaveAction;
    
    private Gtk.Action ExportAction;
    
    private Gtk.Action AboutAction;
    
    private Gtk.Action convertAction;
    
    private Gtk.Action goDownAction;
    
    private Gtk.ToggleAction ShowUnavailableCachesAction;
    
    private Gtk.ToggleAction ShowArchivedCachesAction;
    
    private Gtk.ToggleAction ShowCachesPlacedByMeAction;
    
    private Gtk.Action ClearAllFiltersAction;
    
    private Gtk.Action FilterAction;
    
    private Gtk.ToggleAction ShowFoundCachesAction;
    
    private Gtk.Action printAction;
    
    private Gtk.Action findAction;
    
    private Gtk.Action SearchAction;
    
    private Gtk.Action printPreviewAction;
    
    private Gtk.Action preferencesAction;
    
    private Gtk.Action MapAction;
    
    private Gtk.Action MapAction1;
    
    private Gtk.Action GPSAction;
    
    private Gtk.Action CacheAction;
    
    private Gtk.Action ViewOnlineAction;
    
    private Gtk.Action DeleteAction;
    
    private Gtk.Action goUpAction;
    
    private Gtk.Action newAction;
    
    private Gtk.Action openAction1;
    
    private Gtk.Action GeocachingComAction;
    
    private Gtk.Action ViewCacheOnlineAction;
    
    private Gtk.Action ViewMyProfileAction;
    
    private Gtk.Action CreatePocketQueriesAction;
    
    private Gtk.Action FindACacheAction;
    
    private Gtk.Action LogCacheAction;
    
    private Gtk.Action HomePageAction;
    
    private Gtk.Action MyAccountDetailsAction;
    
    private Gtk.Action newAction1;
    
    private Gtk.Action openAction2;
    
    private Gtk.Action goDownAction1;
    
    private Gtk.Action goUpAction1;
    
    private Gtk.Action PreferencesAction;
    
    private Gtk.Action LogFindAction;
    
    private Gtk.Action MarkUnfoundAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar mainmenubar;
    
    private Gtk.HPaned hSplitPane;
    
    private ocmgtk.CacheList cacheList;
    
    private ocmgtk.GeoCachePane cachePane;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("_File");
        w1.Add(this.FileAction, "<Alt><Mod2>f");
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.QuitAction, null);
        this.EditAction = new Gtk.Action("EditAction", Mono.Unix.Catalog.GetString("_Edit"), null, null);
        this.EditAction.Sensitive = false;
        this.EditAction.ShortLabel = Mono.Unix.Catalog.GetString("Edit");
        w1.Add(this.EditAction, null);
        this.ViewAction = new Gtk.Action("ViewAction", Mono.Unix.Catalog.GetString("View"), null, null);
        this.ViewAction.ShortLabel = Mono.Unix.Catalog.GetString("View");
        w1.Add(this.ViewAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("_Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.openAction = new Gtk.Action("openAction", null, null, "gtk-open");
        w1.Add(this.openAction, null);
        this.saveAction = new Gtk.Action("saveAction", null, null, "gtk-save");
        w1.Add(this.saveAction, null);
        this.saveAsAction = new Gtk.Action("saveAsAction", null, null, "gtk-save-as");
        w1.Add(this.saveAsAction, null);
        this.OpenAction = new Gtk.Action("OpenAction", Mono.Unix.Catalog.GetString("Open"), null, null);
        this.OpenAction.ShortLabel = Mono.Unix.Catalog.GetString("Open");
        w1.Add(this.OpenAction, null);
        this.SaveAction = new Gtk.Action("SaveAction", Mono.Unix.Catalog.GetString("Save"), null, null);
        this.SaveAction.ShortLabel = Mono.Unix.Catalog.GetString("Save");
        w1.Add(this.SaveAction, null);
        this.ExportAction = new Gtk.Action("ExportAction", Mono.Unix.Catalog.GetString("Export..."), null, null);
        this.ExportAction.ShortLabel = Mono.Unix.Catalog.GetString("Export...");
        w1.Add(this.ExportAction, null);
        this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, "gtk-about");
        this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction, null);
        this.convertAction = new Gtk.Action("convertAction", null, null, "gtk-convert");
        w1.Add(this.convertAction, null);
        this.goDownAction = new Gtk.Action("goDownAction", Mono.Unix.Catalog.GetString("Import GPX..."), null, "gtk-go-down");
        this.goDownAction.ShortLabel = Mono.Unix.Catalog.GetString("Import GPX...");
        w1.Add(this.goDownAction, null);
        this.ShowUnavailableCachesAction = new Gtk.ToggleAction("ShowUnavailableCachesAction", Mono.Unix.Catalog.GetString("Show Unavailable Caches"), null, null);
        this.ShowUnavailableCachesAction.Active = true;
        this.ShowUnavailableCachesAction.ShortLabel = Mono.Unix.Catalog.GetString("Show Unavailable Caches");
        w1.Add(this.ShowUnavailableCachesAction, null);
        this.ShowArchivedCachesAction = new Gtk.ToggleAction("ShowArchivedCachesAction", Mono.Unix.Catalog.GetString("Show Archived Caches"), null, null);
        this.ShowArchivedCachesAction.Active = true;
        this.ShowArchivedCachesAction.ShortLabel = Mono.Unix.Catalog.GetString("Show Archived Caches");
        w1.Add(this.ShowArchivedCachesAction, null);
        this.ShowCachesPlacedByMeAction = new Gtk.ToggleAction("ShowCachesPlacedByMeAction", Mono.Unix.Catalog.GetString("Show Caches Placed by Me"), null, null);
        this.ShowCachesPlacedByMeAction.Active = true;
        this.ShowCachesPlacedByMeAction.ShortLabel = Mono.Unix.Catalog.GetString("Show Caches Placed by Me");
        w1.Add(this.ShowCachesPlacedByMeAction, null);
        this.ClearAllFiltersAction = new Gtk.Action("ClearAllFiltersAction", Mono.Unix.Catalog.GetString("Clear All Filters"), null, null);
        this.ClearAllFiltersAction.ShortLabel = Mono.Unix.Catalog.GetString("Clear All Filters");
        w1.Add(this.ClearAllFiltersAction, null);
        this.FilterAction = new Gtk.Action("FilterAction", Mono.Unix.Catalog.GetString("Filter..."), null, null);
        this.FilterAction.ShortLabel = Mono.Unix.Catalog.GetString("Filter...");
        w1.Add(this.FilterAction, null);
        this.ShowFoundCachesAction = new Gtk.ToggleAction("ShowFoundCachesAction", Mono.Unix.Catalog.GetString("Show Found Caches"), null, null);
        this.ShowFoundCachesAction.Active = true;
        this.ShowFoundCachesAction.ShortLabel = Mono.Unix.Catalog.GetString("Show Found Caches");
        w1.Add(this.ShowFoundCachesAction, null);
        this.printAction = new Gtk.Action("printAction", null, null, "gtk-print");
        w1.Add(this.printAction, null);
        this.findAction = new Gtk.Action("findAction", null, null, "gtk-find");
        w1.Add(this.findAction, null);
        this.SearchAction = new Gtk.Action("SearchAction", Mono.Unix.Catalog.GetString("Search"), null, null);
        this.SearchAction.ShortLabel = Mono.Unix.Catalog.GetString("Search");
        w1.Add(this.SearchAction, null);
        this.printPreviewAction = new Gtk.Action("printPreviewAction", null, null, "gtk-print-preview");
        w1.Add(this.printPreviewAction, null);
        this.preferencesAction = new Gtk.Action("preferencesAction", null, null, "gtk-preferences");
        w1.Add(this.preferencesAction, null);
        this.MapAction = new Gtk.Action("MapAction", Mono.Unix.Catalog.GetString("_Map"), null, "map");
        this.MapAction.ShortLabel = Mono.Unix.Catalog.GetString("_Map");
        w1.Add(this.MapAction, null);
        this.MapAction1 = new Gtk.Action("MapAction1", Mono.Unix.Catalog.GetString("_Map"), null, "map");
        this.MapAction1.Sensitive = false;
        this.MapAction1.ShortLabel = Mono.Unix.Catalog.GetString("_Map");
        w1.Add(this.MapAction1, null);
        this.GPSAction = new Gtk.Action("GPSAction", Mono.Unix.Catalog.GetString("G_PS"), null, null);
        this.GPSAction.Sensitive = false;
        this.GPSAction.ShortLabel = Mono.Unix.Catalog.GetString("GPS");
        w1.Add(this.GPSAction, null);
        this.CacheAction = new Gtk.Action("CacheAction", Mono.Unix.Catalog.GetString("_Cache"), null, null);
        this.CacheAction.Sensitive = false;
        this.CacheAction.ShortLabel = Mono.Unix.Catalog.GetString("Cache");
        w1.Add(this.CacheAction, null);
        this.ViewOnlineAction = new Gtk.Action("ViewOnlineAction", Mono.Unix.Catalog.GetString("_View Online"), null, "gtk-info");
        this.ViewOnlineAction.ShortLabel = Mono.Unix.Catalog.GetString("_View Online");
        w1.Add(this.ViewOnlineAction, null);
        this.DeleteAction = new Gtk.Action("DeleteAction", Mono.Unix.Catalog.GetString("_Delete"), null, "gtk-delete");
        this.DeleteAction.ShortLabel = Mono.Unix.Catalog.GetString("_Delete");
        w1.Add(this.DeleteAction, null);
        this.goUpAction = new Gtk.Action("goUpAction", Mono.Unix.Catalog.GetString("Export GPX..."), null, "gtk-go-up");
        this.goUpAction.ShortLabel = Mono.Unix.Catalog.GetString("Export GPX...");
        w1.Add(this.goUpAction, null);
        this.newAction = new Gtk.Action("newAction", Mono.Unix.Catalog.GetString("_New Database..."), null, "gtk-new");
        this.newAction.ShortLabel = Mono.Unix.Catalog.GetString("_New Database...");
        w1.Add(this.newAction, null);
        this.openAction1 = new Gtk.Action("openAction1", Mono.Unix.Catalog.GetString("Open Database..."), null, "gtk-open");
        this.openAction1.ShortLabel = Mono.Unix.Catalog.GetString("Open Database...");
        w1.Add(this.openAction1, null);
        this.GeocachingComAction = new Gtk.Action("GeocachingComAction", Mono.Unix.Catalog.GetString("_Geocaching.com"), null, null);
        this.GeocachingComAction.ShortLabel = Mono.Unix.Catalog.GetString("_Geocaching.com");
        w1.Add(this.GeocachingComAction, null);
        this.ViewCacheOnlineAction = new Gtk.Action("ViewCacheOnlineAction", Mono.Unix.Catalog.GetString("View Cache Online..."), null, null);
        this.ViewCacheOnlineAction.Sensitive = false;
        this.ViewCacheOnlineAction.ShortLabel = Mono.Unix.Catalog.GetString("View Cache Online...");
        w1.Add(this.ViewCacheOnlineAction, null);
        this.ViewMyProfileAction = new Gtk.Action("ViewMyProfileAction", Mono.Unix.Catalog.GetString("View My Profile..."), null, null);
        this.ViewMyProfileAction.ShortLabel = Mono.Unix.Catalog.GetString("View My Profile...");
        w1.Add(this.ViewMyProfileAction, null);
        this.CreatePocketQueriesAction = new Gtk.Action("CreatePocketQueriesAction", Mono.Unix.Catalog.GetString("Create Pocket Queries..."), null, null);
        this.CreatePocketQueriesAction.ShortLabel = Mono.Unix.Catalog.GetString("Create Pocket Queries...");
        w1.Add(this.CreatePocketQueriesAction, null);
        this.FindACacheAction = new Gtk.Action("FindACacheAction", Mono.Unix.Catalog.GetString("Find a Cache..."), null, null);
        this.FindACacheAction.ShortLabel = Mono.Unix.Catalog.GetString("Find a Cache...");
        w1.Add(this.FindACacheAction, null);
        this.LogCacheAction = new Gtk.Action("LogCacheAction", Mono.Unix.Catalog.GetString("Log Cache..."), null, null);
        this.LogCacheAction.Sensitive = false;
        this.LogCacheAction.ShortLabel = Mono.Unix.Catalog.GetString("Log Cache...");
        w1.Add(this.LogCacheAction, null);
        this.HomePageAction = new Gtk.Action("HomePageAction", Mono.Unix.Catalog.GetString("Home Page..."), null, null);
        this.HomePageAction.ShortLabel = Mono.Unix.Catalog.GetString("Home Page...");
        w1.Add(this.HomePageAction, null);
        this.MyAccountDetailsAction = new Gtk.Action("MyAccountDetailsAction", Mono.Unix.Catalog.GetString("My Account Details..."), null, null);
        this.MyAccountDetailsAction.ShortLabel = Mono.Unix.Catalog.GetString("My Account Details...");
        w1.Add(this.MyAccountDetailsAction, null);
        this.newAction1 = new Gtk.Action("newAction1", Mono.Unix.Catalog.GetString("New Database..."), null, "gtk-new");
        this.newAction1.ShortLabel = Mono.Unix.Catalog.GetString("New Database...");
        w1.Add(this.newAction1, null);
        this.openAction2 = new Gtk.Action("openAction2", Mono.Unix.Catalog.GetString("Open Database..."), null, "gtk-open");
        this.openAction2.ShortLabel = Mono.Unix.Catalog.GetString("Open Database...");
        w1.Add(this.openAction2, null);
        this.goDownAction1 = new Gtk.Action("goDownAction1", Mono.Unix.Catalog.GetString("Import GPX..."), null, "gtk-go-down");
        this.goDownAction1.ShortLabel = Mono.Unix.Catalog.GetString("Import GPX...");
        w1.Add(this.goDownAction1, null);
        this.goUpAction1 = new Gtk.Action("goUpAction1", Mono.Unix.Catalog.GetString("Export GPX..."), null, "gtk-go-up");
        this.goUpAction1.ShortLabel = Mono.Unix.Catalog.GetString("Export GPX...");
        w1.Add(this.goUpAction1, null);
        this.PreferencesAction = new Gtk.Action("PreferencesAction", Mono.Unix.Catalog.GetString("Preferences..."), null, null);
        this.PreferencesAction.ShortLabel = Mono.Unix.Catalog.GetString("Preferences...");
        w1.Add(this.PreferencesAction, null);
        this.LogFindAction = new Gtk.Action("LogFindAction", Mono.Unix.Catalog.GetString("Log Find"), null, null);
        this.LogFindAction.ShortLabel = Mono.Unix.Catalog.GetString("Log Find");
        w1.Add(this.LogFindAction, null);
        this.MarkUnfoundAction = new Gtk.Action("MarkUnfoundAction", Mono.Unix.Catalog.GetString("Mark Unfound"), null, null);
        this.MarkUnfoundAction.ShortLabel = Mono.Unix.Catalog.GetString("Mark Unfound");
        w1.Add(this.MarkUnfoundAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Open Cache Manager");
        this.Icon = Gdk.Pixbuf.LoadFromResource("ocmgtk.icons.scalable.OCMLogo.svg");
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='mainmenubar'><menu name='FileAction' action='FileAction'><menuitem name='newAction1' action='newAction1'/><menuitem name='openAction2' action='openAction2'/><separator/><menuitem name='goDownAction1' action='goDownAction1'/><menuitem name='goUpAction1' action='goUpAction1'/><separator/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='CacheAction' action='CacheAction'><menuitem name='ViewOnlineAction' action='ViewOnlineAction'/><menuitem name='LogFindAction' action='LogFindAction'/><menuitem name='MarkUnfoundAction' action='MarkUnfoundAction'/><separator/></menu><menu name='GeocachingComAction' action='GeocachingComAction'><menuitem name='HomePageAction' action='HomePageAction'/><menuitem name='ViewMyProfileAction' action='ViewMyProfileAction'/><menuitem name='MyAccountDetailsAction' action='MyAccountDetailsAction'/><menuitem name='CreatePocketQueriesAction' action='CreatePocketQueriesAction'/><separator/><menuitem name='FindACacheAction' action='FindACacheAction'/><menuitem name='ViewCacheOnlineAction' action='ViewCacheOnlineAction'/><menuitem name='LogCacheAction' action='LogCacheAction'/></menu><menu name='GPSAction' action='GPSAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
        this.mainmenubar = ((Gtk.MenuBar)(this.UIManager.GetWidget("/mainmenubar")));
        this.mainmenubar.Name = "mainmenubar";
        this.vbox1.Add(this.mainmenubar);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.mainmenubar]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hSplitPane = new Gtk.HPaned();
        this.hSplitPane.CanFocus = true;
        this.hSplitPane.Name = "hSplitPane";
        this.hSplitPane.Position = 400;
        this.hSplitPane.BorderWidth = ((uint)(6));
        // Container child hSplitPane.Gtk.Paned+PanedChild
        this.cacheList = new ocmgtk.CacheList();
        this.cacheList.Events = ((Gdk.EventMask)(256));
        this.cacheList.Name = "cacheList";
        this.hSplitPane.Add(this.cacheList);
        Gtk.Paned.PanedChild w3 = ((Gtk.Paned.PanedChild)(this.hSplitPane[this.cacheList]));
        w3.Resize = false;
        // Container child hSplitPane.Gtk.Paned+PanedChild
        this.cachePane = new ocmgtk.GeoCachePane();
        this.cachePane.Events = ((Gdk.EventMask)(256));
        this.cachePane.Name = "cachePane";
        this.hSplitPane.Add(this.cachePane);
        this.vbox1.Add(this.hSplitPane);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.hSplitPane]));
        w5.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.statusbar1.BorderWidth = ((uint)(6));
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w6.PackType = ((Gtk.PackType)(1));
        w6.Position = 2;
        w6.Expand = false;
        w6.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 1284;
        this.DefaultHeight = 1201;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.QuitAction.Activated += new System.EventHandler(this.OnQuit);
        this.AboutAction.Activated += new System.EventHandler(this.doAbout);
        this.goDownAction.Activated += new System.EventHandler(this.OnImportClicked);
        this.ShowUnavailableCachesAction.Toggled += new System.EventHandler(this.OnToggleUnavailable);
        this.ShowArchivedCachesAction.Toggled += new System.EventHandler(this.OnToggleArchive);
        this.ShowCachesPlacedByMeAction.Toggled += new System.EventHandler(this.OnToggleMine);
        this.ShowFoundCachesAction.Toggled += new System.EventHandler(this.OnToggleFound);
        this.preferencesAction.Activated += new System.EventHandler(this.OnPreferences);
        this.MapAction1.Activated += new System.EventHandler(this.OnMapClick);
        this.ViewOnlineAction.Activated += new System.EventHandler(this.OnViewOnline);
        this.goUpAction.Activated += new System.EventHandler(this.OnExportClicked);
        this.newAction.Activated += new System.EventHandler(this.OnNewActionActivated);
        this.openAction1.Activated += new System.EventHandler(this.OnOpenDatabaseClicked);
        this.ViewCacheOnlineAction.Activated += new System.EventHandler(this.OnViewOnlineActivate);
        this.ViewMyProfileAction.Activated += new System.EventHandler(this.OnViewProfileActivate);
        this.CreatePocketQueriesAction.Activated += new System.EventHandler(this.OnPocketQueryActivate);
        this.FindACacheAction.Activated += new System.EventHandler(this.OnFindOnlineActivate);
        this.LogCacheAction.Activated += new System.EventHandler(this.OnLogActivate);
        this.HomePageAction.Activated += new System.EventHandler(this.OnHomePageActivate);
        this.MyAccountDetailsAction.Activated += new System.EventHandler(this.OnAccountActivated);
        this.newAction1.Activated += new System.EventHandler(this.OnNewActionActivated);
        this.openAction2.Activated += new System.EventHandler(this.OnOpenDatabaseClicked);
        this.goDownAction1.Activated += new System.EventHandler(this.OnImportClicked);
        this.goUpAction1.Activated += new System.EventHandler(this.OnExportClicked);
        this.LogFindAction.Activated += new System.EventHandler(this.OnClickLog);
        this.MarkUnfoundAction.Activated += new System.EventHandler(this.OnClickMarkUnfound);
    }
}
