// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class WaypointDialog {
        
        private Gtk.Table table1;
        
        private Gtk.Alignment alignment2;
        
        private Gtk.Entry nameEntry;
        
        private Gtk.Alignment alignment3;
        
        private Gtk.ComboBox flagEntry;
        
        private Gtk.Alignment alignment4;
        
        private ocmgtk.LocationWidget locationWidget;
        
        private Gtk.Alignment alignment7;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView descriptionEntry;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Label label1;
        
        private Gtk.Label label5;
        
        private Gtk.Label label7;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.WaypointDialog
            this.Name = "ocmgtk.WaypointDialog";
            this.Title = Mono.Unix.Catalog.GetString("Add/Edit Waypoint...");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.BorderWidth = ((uint)(6));
            // Internal child ocmgtk.WaypointDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.alignment2 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            this.alignment2.TopPadding = ((uint)(6));
            this.alignment2.RightPadding = ((uint)(12));
            // Container child alignment2.Gtk.Container+ContainerChild
            this.nameEntry = new Gtk.Entry();
            this.nameEntry.CanFocus = true;
            this.nameEntry.Name = "nameEntry";
            this.nameEntry.IsEditable = true;
            this.nameEntry.InvisibleChar = '•';
            this.alignment2.Add(this.nameEntry);
            this.table1.Add(this.alignment2);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.alignment2]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment3 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment3.Name = "alignment3";
            this.alignment3.TopPadding = ((uint)(6));
            this.alignment3.RightPadding = ((uint)(12));
            // Container child alignment3.Gtk.Container+ContainerChild
            this.flagEntry = Gtk.ComboBox.NewText();
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Final Location"));
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Parking Area"));
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Question To Answer"));
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Reference Point"));
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Stages of a Multicache"));
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Trailhead"));
            this.flagEntry.AppendText(Mono.Unix.Catalog.GetString("Other"));
            this.flagEntry.Name = "flagEntry";
            this.flagEntry.Active = 0;
            this.alignment3.Add(this.flagEntry);
            this.table1.Add(this.alignment3);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.alignment3]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment4 = new Gtk.Alignment(0F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            this.alignment4.TopPadding = ((uint)(6));
            this.alignment4.RightPadding = ((uint)(12));
            // Container child alignment4.Gtk.Container+ContainerChild
            this.locationWidget = new ocmgtk.LocationWidget();
            this.locationWidget.Events = ((Gdk.EventMask)(256));
            this.locationWidget.Name = "locationWidget";
            this.locationWidget.Latitude = 0;
            this.locationWidget.Longitude = 0;
            this.alignment4.Add(this.locationWidget);
            this.table1.Add(this.alignment4);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.alignment4]));
            w7.TopAttach = ((uint)(3));
            w7.BottomAttach = ((uint)(4));
            w7.RightAttach = ((uint)(2));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment7 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            this.alignment7.TopPadding = ((uint)(6));
            this.alignment7.RightPadding = ((uint)(12));
            // Container child alignment7.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.descriptionEntry = new Gtk.TextView();
            this.descriptionEntry.CanFocus = true;
            this.descriptionEntry.Name = "descriptionEntry";
            this.GtkScrolledWindow.Add(this.descriptionEntry);
            this.alignment7.Add(this.GtkScrolledWindow);
            this.table1.Add(this.alignment7);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.alignment7]));
            w10.TopAttach = ((uint)(5));
            w10.BottomAttach = ((uint)(6));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.table1.Add(this.hseparator1);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.hseparator1]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.table1.Add(this.hseparator2);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.hseparator2]));
            w12.TopAttach = ((uint)(4));
            w12.BottomAttach = ((uint)(5));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Symbol:");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Ypad = 6;
            this.label7.Xalign = 0F;
            this.label7.Yalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Description:");
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w15.TopAttach = ((uint)(5));
            w15.BottomAttach = ((uint)(6));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Internal child ocmgtk.WaypointDialog.ActionArea
            Gtk.HButtonBox w17 = this.ActionArea;
            w17.Name = "dialog1_ActionArea";
            w17.Spacing = 10;
            w17.BorderWidth = ((uint)(5));
            w17.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w18 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonCancel]));
            w18.Expand = false;
            w18.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w19 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonOk]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 704;
            this.DefaultHeight = 385;
            this.Show();
            this.flagEntry.Changed += new System.EventHandler(this.OnSelectionChanged);
            this.buttonCancel.Clicked += new System.EventHandler(this.OnButtonCancelClicked);
            this.buttonOk.Clicked += new System.EventHandler(this.OnOKClicked);
        }
    }
}
