// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class OCMQueryPage1 {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Table table1;
        
        private Gtk.RadioButton allCacheRadio;
        
        private Gtk.CheckButton diffCheck;
        
        private Gtk.ComboBox diffRange;
        
        private Gtk.ComboBox diffValue;
        
        private Gtk.Frame selCacheFrame;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table2;
        
        private Gtk.CheckButton advCheck;
        
        private Gtk.CheckButton apeCheck;
        
        private Gtk.CheckButton citoCheck;
        
        private Gtk.CheckButton earCheck;
        
        private Gtk.CheckButton evntCheck;
        
        private Gtk.CheckButton lettCheck;
        
        private Gtk.CheckButton locCheck;
        
        private Gtk.CheckButton megaCheck;
        
        private Gtk.CheckButton multiCheck;
        
        private Gtk.CheckButton tradCheck;
        
        private Gtk.CheckButton unkCheck;
        
        private Gtk.CheckButton virtCheck;
        
        private Gtk.CheckButton webCheck;
        
        private Gtk.CheckButton wherigoCheck;
        
        private Gtk.Label GtkLabel15;
        
        private Gtk.RadioButton selCacheRadio;
        
        private Gtk.CheckButton terrainCheck;
        
        private Gtk.ComboBox terrRange;
        
        private Gtk.ComboBox terrValue;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.OCMQueryPage1
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.OCMQueryPage1";
            // Container child ocmgtk.OCMQueryPage1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.allCacheRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("All Cache Types"));
            this.allCacheRadio.CanFocus = true;
            this.allCacheRadio.Name = "allCacheRadio";
            this.allCacheRadio.Active = true;
            this.allCacheRadio.DrawIndicator = true;
            this.allCacheRadio.UseUnderline = true;
            this.allCacheRadio.Group = new GLib.SList(System.IntPtr.Zero);
            this.table1.Add(this.allCacheRadio);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.allCacheRadio]));
            w1.TopAttach = ((uint)(2));
            w1.BottomAttach = ((uint)(3));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.diffCheck = new Gtk.CheckButton();
            this.diffCheck.CanFocus = true;
            this.diffCheck.Name = "diffCheck";
            this.diffCheck.Label = Mono.Unix.Catalog.GetString("Difficulty");
            this.diffCheck.DrawIndicator = true;
            this.diffCheck.UseUnderline = true;
            this.table1.Add(this.diffCheck);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.diffCheck]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.diffRange = Gtk.ComboBox.NewText();
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than or Equal To"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Equal To"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Less Than or Equal To"));
            this.diffRange.AppendText(Mono.Unix.Catalog.GetString("Less Than"));
            this.diffRange.Sensitive = false;
            this.diffRange.Name = "diffRange";
            this.diffRange.Active = 0;
            this.table1.Add(this.diffRange);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.diffRange]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.diffValue = Gtk.ComboBox.NewText();
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("1"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("1.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("2"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("2.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("3"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("3.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("4"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("4.5"));
            this.diffValue.AppendText(Mono.Unix.Catalog.GetString("5"));
            this.diffValue.Sensitive = false;
            this.diffValue.Name = "diffValue";
            this.diffValue.Active = 0;
            this.table1.Add(this.diffValue);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.diffValue]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.LeftAttach = ((uint)(2));
            w4.RightAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selCacheFrame = new Gtk.Frame();
            this.selCacheFrame.Sensitive = false;
            this.selCacheFrame.Name = "selCacheFrame";
            // Container child selCacheFrame.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.table2.BorderWidth = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.advCheck = new Gtk.CheckButton();
            this.advCheck.CanFocus = true;
            this.advCheck.Name = "advCheck";
            this.advCheck.Label = Mono.Unix.Catalog.GetString("Adventure Maze");
            this.advCheck.DrawIndicator = true;
            this.advCheck.UseUnderline = true;
            this.table2.Add(this.advCheck);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.advCheck]));
            w5.TopAttach = ((uint)(3));
            w5.BottomAttach = ((uint)(4));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.apeCheck = new Gtk.CheckButton();
            this.apeCheck.CanFocus = true;
            this.apeCheck.Name = "apeCheck";
            this.apeCheck.Label = Mono.Unix.Catalog.GetString("A.P.E.");
            this.apeCheck.DrawIndicator = true;
            this.apeCheck.UseUnderline = true;
            this.table2.Add(this.apeCheck);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.apeCheck]));
            w6.TopAttach = ((uint)(4));
            w6.BottomAttach = ((uint)(5));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.citoCheck = new Gtk.CheckButton();
            this.citoCheck.CanFocus = true;
            this.citoCheck.Name = "citoCheck";
            this.citoCheck.Label = Mono.Unix.Catalog.GetString("CITO");
            this.citoCheck.DrawIndicator = true;
            this.citoCheck.UseUnderline = true;
            this.table2.Add(this.citoCheck);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this.citoCheck]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.LeftAttach = ((uint)(2));
            w7.RightAttach = ((uint)(3));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.earCheck = new Gtk.CheckButton();
            this.earCheck.CanFocus = true;
            this.earCheck.Name = "earCheck";
            this.earCheck.Label = Mono.Unix.Catalog.GetString("Earth Cache");
            this.earCheck.DrawIndicator = true;
            this.earCheck.UseUnderline = true;
            this.table2.Add(this.earCheck);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this.earCheck]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.evntCheck = new Gtk.CheckButton();
            this.evntCheck.CanFocus = true;
            this.evntCheck.Name = "evntCheck";
            this.evntCheck.Label = Mono.Unix.Catalog.GetString("Event Cache");
            this.evntCheck.DrawIndicator = true;
            this.evntCheck.UseUnderline = true;
            this.table2.Add(this.evntCheck);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.evntCheck]));
            w9.LeftAttach = ((uint)(2));
            w9.RightAttach = ((uint)(3));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lettCheck = new Gtk.CheckButton();
            this.lettCheck.CanFocus = true;
            this.lettCheck.Name = "lettCheck";
            this.lettCheck.Label = Mono.Unix.Catalog.GetString("Letterbox Hybrid");
            this.lettCheck.DrawIndicator = true;
            this.lettCheck.UseUnderline = true;
            this.table2.Add(this.lettCheck);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table2[this.lettCheck]));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.locCheck = new Gtk.CheckButton();
            this.locCheck.CanFocus = true;
            this.locCheck.Name = "locCheck";
            this.locCheck.Label = Mono.Unix.Catalog.GetString("Locationless");
            this.locCheck.DrawIndicator = true;
            this.locCheck.UseUnderline = true;
            this.table2.Add(this.locCheck);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table2[this.locCheck]));
            w11.TopAttach = ((uint)(4));
            w11.BottomAttach = ((uint)(5));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.megaCheck = new Gtk.CheckButton();
            this.megaCheck.CanFocus = true;
            this.megaCheck.Name = "megaCheck";
            this.megaCheck.Label = Mono.Unix.Catalog.GetString("Mega Event");
            this.megaCheck.DrawIndicator = true;
            this.megaCheck.UseUnderline = true;
            this.table2.Add(this.megaCheck);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table2[this.megaCheck]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.LeftAttach = ((uint)(2));
            w12.RightAttach = ((uint)(3));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.multiCheck = new Gtk.CheckButton();
            this.multiCheck.CanFocus = true;
            this.multiCheck.Name = "multiCheck";
            this.multiCheck.Label = Mono.Unix.Catalog.GetString("Multi-Cache");
            this.multiCheck.DrawIndicator = true;
            this.multiCheck.UseUnderline = true;
            this.table2.Add(this.multiCheck);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table2[this.multiCheck]));
            w13.TopAttach = ((uint)(1));
            w13.BottomAttach = ((uint)(2));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.tradCheck = new Gtk.CheckButton();
            this.tradCheck.CanFocus = true;
            this.tradCheck.Name = "tradCheck";
            this.tradCheck.Label = Mono.Unix.Catalog.GetString("Traditional");
            this.tradCheck.DrawIndicator = true;
            this.tradCheck.UseUnderline = true;
            this.table2.Add(this.tradCheck);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table2[this.tradCheck]));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.unkCheck = new Gtk.CheckButton();
            this.unkCheck.CanFocus = true;
            this.unkCheck.Name = "unkCheck";
            this.unkCheck.Label = Mono.Unix.Catalog.GetString("Unknown");
            this.unkCheck.DrawIndicator = true;
            this.unkCheck.UseUnderline = true;
            this.table2.Add(this.unkCheck);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table2[this.unkCheck]));
            w15.TopAttach = ((uint)(2));
            w15.BottomAttach = ((uint)(3));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.virtCheck = new Gtk.CheckButton();
            this.virtCheck.CanFocus = true;
            this.virtCheck.Name = "virtCheck";
            this.virtCheck.Label = Mono.Unix.Catalog.GetString("Virtual");
            this.virtCheck.DrawIndicator = true;
            this.virtCheck.UseUnderline = true;
            this.table2.Add(this.virtCheck);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table2[this.virtCheck]));
            w16.TopAttach = ((uint)(3));
            w16.BottomAttach = ((uint)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.webCheck = new Gtk.CheckButton();
            this.webCheck.CanFocus = true;
            this.webCheck.Name = "webCheck";
            this.webCheck.Label = Mono.Unix.Catalog.GetString("Webcam");
            this.webCheck.DrawIndicator = true;
            this.webCheck.UseUnderline = true;
            this.table2.Add(this.webCheck);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table2[this.webCheck]));
            w17.TopAttach = ((uint)(3));
            w17.BottomAttach = ((uint)(4));
            w17.LeftAttach = ((uint)(2));
            w17.RightAttach = ((uint)(3));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.wherigoCheck = new Gtk.CheckButton();
            this.wherigoCheck.CanFocus = true;
            this.wherigoCheck.Name = "wherigoCheck";
            this.wherigoCheck.Label = Mono.Unix.Catalog.GetString("Wherigo");
            this.wherigoCheck.DrawIndicator = true;
            this.wherigoCheck.UseUnderline = true;
            this.table2.Add(this.wherigoCheck);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table2[this.wherigoCheck]));
            w18.TopAttach = ((uint)(1));
            w18.BottomAttach = ((uint)(2));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table2);
            this.selCacheFrame.Add(this.GtkAlignment);
            this.GtkLabel15 = new Gtk.Label();
            this.GtkLabel15.Name = "GtkLabel15";
            this.GtkLabel15.LabelProp = Mono.Unix.Catalog.GetString("<b>Cache Types</b>");
            this.GtkLabel15.UseMarkup = true;
            this.selCacheFrame.LabelWidget = this.GtkLabel15;
            this.table1.Add(this.selCacheFrame);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.selCacheFrame]));
            w21.TopAttach = ((uint)(4));
            w21.BottomAttach = ((uint)(5));
            w21.RightAttach = ((uint)(3));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.selCacheRadio = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Selected Cache Types"));
            this.selCacheRadio.CanFocus = true;
            this.selCacheRadio.Name = "selCacheRadio";
            this.selCacheRadio.DrawIndicator = true;
            this.selCacheRadio.UseUnderline = true;
            this.selCacheRadio.Group = this.allCacheRadio.Group;
            this.table1.Add(this.selCacheRadio);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.selCacheRadio]));
            w22.TopAttach = ((uint)(3));
            w22.BottomAttach = ((uint)(4));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.terrainCheck = new Gtk.CheckButton();
            this.terrainCheck.CanFocus = true;
            this.terrainCheck.Name = "terrainCheck";
            this.terrainCheck.Label = Mono.Unix.Catalog.GetString("Terrain");
            this.terrainCheck.DrawIndicator = true;
            this.terrainCheck.UseUnderline = true;
            this.table1.Add(this.terrainCheck);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table1[this.terrainCheck]));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.terrRange = Gtk.ComboBox.NewText();
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Greater Than or Equal To"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Equal To"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Less Than or Equal To"));
            this.terrRange.AppendText(Mono.Unix.Catalog.GetString("Less Than"));
            this.terrRange.Sensitive = false;
            this.terrRange.Name = "terrRange";
            this.terrRange.Active = 0;
            this.table1.Add(this.terrRange);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table1[this.terrRange]));
            w24.LeftAttach = ((uint)(1));
            w24.RightAttach = ((uint)(2));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.terrValue = Gtk.ComboBox.NewText();
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("1"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("1.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("2"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("2.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("3"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("3.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("4"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("4.5"));
            this.terrValue.AppendText(Mono.Unix.Catalog.GetString("5"));
            this.terrValue.Sensitive = false;
            this.terrValue.Name = "terrValue";
            this.terrValue.Active = 0;
            this.table1.Add(this.terrValue);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table1[this.terrValue]));
            w25.LeftAttach = ((uint)(2));
            w25.RightAttach = ((uint)(3));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w26.Position = 0;
            w26.Expand = false;
            w26.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.terrainCheck.Toggled += new System.EventHandler(this.OnTerrToggle);
            this.diffCheck.Toggled += new System.EventHandler(this.OnDiffToggle);
            this.allCacheRadio.Toggled += new System.EventHandler(this.OnCacheToggle);
        }
    }
}
