// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class BrowserWidget {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.VBox widgetBox;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label spacer;
        
        private Gtk.Button sizeUpButton;
        
        private Gtk.Image image1;
        
        private Gtk.Button sizeDownButton;
        
        private Gtk.Image image2;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Frame browserFrame;
        
        private Gtk.Alignment browserAlign;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.BrowserWidget
            Stetic.BinContainer w1 = Stetic.BinContainer.Attach(this);
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.UIManager.InsertActionGroup(w2, 0);
            this.Name = "ocmgtk.BrowserWidget";
            // Container child ocmgtk.BrowserWidget.Gtk.Container+ContainerChild
            this.widgetBox = new Gtk.VBox();
            this.widgetBox.Name = "widgetBox";
            // Container child widgetBox.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.spacer = new Gtk.Label();
            this.spacer.Name = "spacer";
            this.hbox1.Add(this.spacer);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.spacer]));
            w3.Position = 0;
            w3.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.sizeUpButton = new Gtk.Button();
            this.sizeUpButton.CanFocus = true;
            this.sizeUpButton.Name = "sizeUpButton";
            this.sizeUpButton.FocusOnClick = false;
            this.sizeUpButton.Relief = ((Gtk.ReliefStyle)(2));
            // Container child sizeUpButton.Gtk.Container+ContainerChild
            this.image1 = new Gtk.Image();
            this.image1.Name = "image1";
            this.image1.Pixbuf = Gdk.Pixbuf.LoadFromResource("ocmgtk.icons.scalable.up_icon.svg");
            this.sizeUpButton.Add(this.image1);
            this.sizeUpButton.Label = null;
            this.hbox1.Add(this.sizeUpButton);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.sizeUpButton]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.sizeDownButton = new Gtk.Button();
            this.sizeDownButton.CanFocus = true;
            this.sizeDownButton.Name = "sizeDownButton";
            this.sizeDownButton.FocusOnClick = false;
            this.sizeDownButton.Relief = ((Gtk.ReliefStyle)(2));
            // Container child sizeDownButton.Gtk.Container+ContainerChild
            this.image2 = new Gtk.Image();
            this.image2.Name = "image2";
            this.image2.Pixbuf = Gdk.Pixbuf.LoadFromResource("ocmgtk.icons.scalable.down_icon.svg");
            this.sizeDownButton.Add(this.image2);
            this.sizeDownButton.Label = null;
            this.hbox1.Add(this.sizeDownButton);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.sizeDownButton]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.widgetBox.Add(this.hbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.widgetBox[this.hbox1]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child widgetBox.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            this.widgetBox.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.widgetBox[this.hbuttonbox2]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child widgetBox.Gtk.Box+BoxChild
            this.browserFrame = new Gtk.Frame();
            this.browserFrame.Name = "browserFrame";
            this.browserFrame.ShadowType = ((Gtk.ShadowType)(1));
            this.browserFrame.LabelYalign = 0F;
            // Container child browserFrame.Gtk.Container+ContainerChild
            this.browserAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.browserAlign.Name = "browserAlign";
            this.browserFrame.Add(this.browserAlign);
            this.widgetBox.Add(this.browserFrame);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.widgetBox[this.browserFrame]));
            w11.Position = 2;
            this.Add(this.widgetBox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            w1.SetUiManager(UIManager);
            this.Hide();
            this.sizeUpButton.Clicked += new System.EventHandler(this.OnUpClick);
            this.sizeDownButton.Clicked += new System.EventHandler(this.OnDownClick);
        }
    }
}
