// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class AttributeFilterWidget {
        
        private Gtk.Button attrIconButton;
        
        private Gtk.Image attrIcon;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.AttributeFilterWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.AttributeFilterWidget";
            // Container child ocmgtk.AttributeFilterWidget.Gtk.Container+ContainerChild
            this.attrIconButton = new Gtk.Button();
            this.attrIconButton.WidthRequest = 45;
            this.attrIconButton.HeightRequest = 45;
            this.attrIconButton.CanFocus = true;
            this.attrIconButton.Name = "attrIconButton";
            this.attrIconButton.FocusOnClick = false;
            this.attrIconButton.Relief = ((Gtk.ReliefStyle)(1));
            // Container child attrIconButton.Gtk.Container+ContainerChild
            this.attrIcon = new Gtk.Image();
            this.attrIcon.Name = "attrIcon";
            this.attrIconButton.Add(this.attrIcon);
            this.attrIconButton.Label = null;
            this.Add(this.attrIconButton);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.attrIconButton.Clicked += new System.EventHandler(this.OnClick);
        }
    }
}
