// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class InternalBrowser {
        
        private Gtk.VBox vbox1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.Statusbar browserStatus;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.InternalBrowser
            this.Name = "ocmgtk.InternalBrowser";
            this.Title = Mono.Unix.Catalog.GetString("OCM Browser");
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            // Container child ocmgtk.InternalBrowser.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.BorderWidth = ((uint)(2));
            // Container child vbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
            w1.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.browserStatus = new Gtk.Statusbar();
            this.browserStatus.Name = "browserStatus";
            this.browserStatus.Spacing = 6;
            this.vbox1.Add(this.browserStatus);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.browserStatus]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 936;
            this.DefaultHeight = 695;
            this.Show();
        }
    }
}
