// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class OCMQueryPage5 {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Frame inclAttrFrame;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table2;
        
        private ocmgtk.AttributeFilterWidget beaconFilt;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Image image3;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private ocmgtk.AttributeFilterWidget maintenanceAttr;
        
        private ocmgtk.AttributeFilterWidget nightAttr;
        
        private ocmgtk.AttributeFilterWidget winterAttr;
        
        private Gtk.Label GtkLabel15;
        
        private Gtk.Table table3;
        
        private Gtk.CheckButton altExcludeCheck;
        
        private Gtk.CheckButton altIncludeCheck;
        
        private Gtk.Entry entry1;
        
        private Gtk.Entry entry2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.OCMQueryPage5
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.OCMQueryPage5";
            // Container child ocmgtk.OCMQueryPage5.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(6));
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.inclAttrFrame = new Gtk.Frame();
            this.inclAttrFrame.Name = "inclAttrFrame";
            // Container child inclAttrFrame.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(5)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(2));
            this.table2.ColumnSpacing = ((uint)(2));
            this.table2.BorderWidth = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.beaconFilt = new ocmgtk.AttributeFilterWidget();
            this.beaconFilt.Events = ((Gdk.EventMask)(256));
            this.beaconFilt.Name = "beaconFilt";
            this.beaconFilt.AttributeName = "Wireless Beacon";
            this.table2.Add(this.beaconFilt);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table2[this.beaconFilt]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(3));
            w1.RightAttach = ((uint)(4));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.image3 = new Gtk.Image();
            this.image3.Name = "image3";
            this.image3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dialog-info", Gtk.IconSize.Button, 20);
            this.hbox1.Add(this.image3);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.image3]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Click on the attribute once to include it. Click twice to exclude it. Click three times to clear.");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.table2.Add(this.hbox1);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.hbox1]));
            w4.RightAttach = ((uint)(5));
            w4.XOptions = ((Gtk.AttachOptions)(0));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.table2.Add(this.label2);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.label2]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(4));
            w5.RightAttach = ((uint)(5));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.maintenanceAttr = new ocmgtk.AttributeFilterWidget();
            this.maintenanceAttr.Events = ((Gdk.EventMask)(256));
            this.maintenanceAttr.Name = "maintenanceAttr";
            this.maintenanceAttr.AttributeName = "Needs maintenance";
            this.table2.Add(this.maintenanceAttr);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.maintenanceAttr]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.nightAttr = new ocmgtk.AttributeFilterWidget();
            this.nightAttr.Events = ((Gdk.EventMask)(256));
            this.nightAttr.Name = "nightAttr";
            this.nightAttr.AttributeName = "Recommended at night";
            this.table2.Add(this.nightAttr);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this.nightAttr]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.LeftAttach = ((uint)(2));
            w7.RightAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.winterAttr = new ocmgtk.AttributeFilterWidget();
            this.winterAttr.Events = ((Gdk.EventMask)(256));
            this.winterAttr.Name = "winterAttr";
            this.winterAttr.AttributeName = "Available during winter";
            this.table2.Add(this.winterAttr);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this.winterAttr]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(0));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table2);
            this.inclAttrFrame.Add(this.GtkAlignment);
            this.GtkLabel15 = new Gtk.Label();
            this.GtkLabel15.Name = "GtkLabel15";
            this.GtkLabel15.LabelProp = Mono.Unix.Catalog.GetString("Common Attributes");
            this.GtkLabel15.UseMarkup = true;
            this.inclAttrFrame.LabelWidget = this.GtkLabel15;
            this.vbox3.Add(this.inclAttrFrame);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox3[this.inclAttrFrame]));
            w11.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.altExcludeCheck = new Gtk.CheckButton();
            this.altExcludeCheck.Sensitive = false;
            this.altExcludeCheck.CanFocus = true;
            this.altExcludeCheck.Name = "altExcludeCheck";
            this.altExcludeCheck.Label = Mono.Unix.Catalog.GetString("Other must exclude attributes (comma seperated):");
            this.altExcludeCheck.DrawIndicator = true;
            this.altExcludeCheck.UseUnderline = true;
            this.table3.Add(this.altExcludeCheck);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table3[this.altExcludeCheck]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.altIncludeCheck = new Gtk.CheckButton();
            this.altIncludeCheck.Sensitive = false;
            this.altIncludeCheck.CanFocus = true;
            this.altIncludeCheck.Name = "altIncludeCheck";
            this.altIncludeCheck.Label = Mono.Unix.Catalog.GetString("Other must have attributes (comma seperated):");
            this.altIncludeCheck.DrawIndicator = true;
            this.altIncludeCheck.UseUnderline = true;
            this.table3.Add(this.altIncludeCheck);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table3[this.altIncludeCheck]));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.entry1 = new Gtk.Entry();
            this.entry1.Sensitive = false;
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '•';
            this.table3.Add(this.entry1);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table3[this.entry1]));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.entry2 = new Gtk.Entry();
            this.entry2.Sensitive = false;
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.IsEditable = true;
            this.entry2.InvisibleChar = '•';
            this.table3.Add(this.entry2);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table3[this.entry2]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table3);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox3[this.table3]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            this.alignment1.Add(this.vbox3);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w18.Position = 0;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
