// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class FilterDialog {
        
        private Gtk.Notebook notebook1;
        
        private ocmgtk.OCMQueryPage1 page1;
        
        private Gtk.Label label3;
        
        private ocmgtk.OCMQueryPage2 contPage;
        
        private Gtk.Label page2;
        
        private ocmgtk.OCMQueryPage3 datePage;
        
        private Gtk.Label label2;
        
        private ocmgtk.OCMQueryPage4 childrenPage;
        
        private Gtk.Label labelChildren;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.FilterDialog
            this.Name = "ocmgtk.FilterDialog";
            this.Title = Mono.Unix.Catalog.GetString("Advanced Filters...");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Internal child ocmgtk.FilterDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 3;
            this.notebook1.TabPos = ((Gtk.PositionType)(0));
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.page1 = new ocmgtk.OCMQueryPage1();
            this.page1.Events = ((Gdk.EventMask)(256));
            this.page1.Name = "page1";
            this.notebook1.Add(this.page1);
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Difficulty/Type");
            this.notebook1.SetTabLabel(this.page1, this.label3);
            this.label3.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.contPage = new ocmgtk.OCMQueryPage2();
            this.contPage.Events = ((Gdk.EventMask)(256));
            this.contPage.Name = "contPage";
            this.contPage.PlacedByMe = false;
            this.notebook1.Add(this.contPage);
            Gtk.Notebook.NotebookChild w3 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.contPage]));
            w3.Position = 1;
            // Notebook tab
            this.page2 = new Gtk.Label();
            this.page2.Name = "page2";
            this.page2.LabelProp = Mono.Unix.Catalog.GetString("Container/Description/Placed By");
            this.notebook1.SetTabLabel(this.contPage, this.page2);
            this.page2.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.datePage = new ocmgtk.OCMQueryPage3();
            this.datePage.Events = ((Gdk.EventMask)(256));
            this.datePage.Name = "datePage";
            this.datePage.PlaceBefore = new System.DateTime(0);
            this.datePage.PlaceAfter = new System.DateTime(0);
            this.datePage.InfoAfter = new System.DateTime(0);
            this.datePage.InfoBefore = new System.DateTime(0);
            this.datePage.FoundOn = new System.DateTime(0);
            this.datePage.FoundBefore = new System.DateTime(0);
            this.datePage.FoundAfter = new System.DateTime(0);
            this.notebook1.Add(this.datePage);
            Gtk.Notebook.NotebookChild w4 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.datePage]));
            w4.Position = 2;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Dates/Location");
            this.notebook1.SetTabLabel(this.datePage, this.label2);
            this.label2.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.childrenPage = new ocmgtk.OCMQueryPage4();
            this.childrenPage.Events = ((Gdk.EventMask)(256));
            this.childrenPage.Name = "childrenPage";
            this.childrenPage.HasNotes = false;
            this.childrenPage.HasCorrectedCoords = false;
            this.childrenPage.DoesNotHaveCorrectedCoords = false;
            this.notebook1.Add(this.childrenPage);
            Gtk.Notebook.NotebookChild w5 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.childrenPage]));
            w5.Position = 3;
            // Notebook tab
            this.labelChildren = new Gtk.Label();
            this.labelChildren.Name = "labelChildren";
            this.labelChildren.LabelProp = Mono.Unix.Catalog.GetString("Notes/Children/Corrected");
            this.notebook1.SetTabLabel(this.childrenPage, this.labelChildren);
            this.labelChildren.ShowAll();
            w1.Add(this.notebook1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(w1[this.notebook1]));
            w6.Position = 0;
            // Internal child ocmgtk.FilterDialog.ActionArea
            Gtk.HButtonBox w7 = this.ActionArea;
            w7.Name = "dialog1_ActionArea";
            w7.Spacing = 10;
            w7.BorderWidth = ((uint)(5));
            w7.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonCancel]));
            w8.Expand = false;
            w8.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonOk]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 673;
            this.DefaultHeight = 453;
            this.buttonOk.HasDefault = true;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteClick);
            this.buttonCancel.Clicked += new System.EventHandler(this.OnCancel);
            this.buttonOk.Clicked += new System.EventHandler(this.OnOKClicked);
        }
    }
}
