// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class HTMLWidget {
        
        private Gtk.Frame frame4;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.Alignment htmlAlign;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.HTMLWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.HTMLWidget";
            // Container child ocmgtk.HTMLWidget.Gtk.Container+ContainerChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(0));
            this.frame4.LabelYalign = 0F;
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.htmlAlign = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.htmlAlign.Name = "htmlAlign";
            w1.Add(this.htmlAlign);
            this.GtkScrolledWindow.Add(w1);
            this.frame4.Add(this.GtkScrolledWindow);
            this.Add(this.frame4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
