// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class OCMQueryPage3 {
        
        private Gtk.Table table2;
        
        private Gtk.CheckButton checkbutton2;
        
        private Gtk.CheckButton checkbutton3;
        
        private Gtk.Entry entry1;
        
        private Gtk.Entry entry2;
        
        private Gtk.Entry limitEntry;
        
        private Gtk.CheckButton placedSince;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.OCMQueryPage3
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.OCMQueryPage3";
            // Container child ocmgtk.OCMQueryPage3.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.table2.BorderWidth = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.checkbutton2 = new Gtk.CheckButton();
            this.checkbutton2.CanFocus = true;
            this.checkbutton2.Name = "checkbutton2";
            this.checkbutton2.Label = Mono.Unix.Catalog.GetString("Limit Number of Caches");
            this.checkbutton2.DrawIndicator = true;
            this.checkbutton2.UseUnderline = true;
            this.table2.Add(this.checkbutton2);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table2[this.checkbutton2]));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.checkbutton3 = new Gtk.CheckButton();
            this.checkbutton3.CanFocus = true;
            this.checkbutton3.Name = "checkbutton3";
            this.checkbutton3.Label = Mono.Unix.Catalog.GetString("Placed Before:");
            this.checkbutton3.DrawIndicator = true;
            this.checkbutton3.UseUnderline = true;
            this.table2.Add(this.checkbutton3);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.checkbutton3]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.entry1 = new Gtk.Entry();
            this.entry1.TooltipMarkup = "M/D/YYYY";
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.Text = Mono.Unix.Catalog.GetString("1/1/2001");
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '•';
            this.table2.Add(this.entry1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.entry1]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.entry2 = new Gtk.Entry();
            this.entry2.TooltipMarkup = "M/D/YYYY";
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.Text = Mono.Unix.Catalog.GetString("1/1/2001");
            this.entry2.IsEditable = true;
            this.entry2.InvisibleChar = '•';
            this.table2.Add(this.entry2);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.entry2]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.limitEntry = new Gtk.Entry();
            this.limitEntry.Sensitive = false;
            this.limitEntry.CanFocus = true;
            this.limitEntry.Name = "limitEntry";
            this.limitEntry.Text = Mono.Unix.Catalog.GetString("1000");
            this.limitEntry.IsEditable = true;
            this.limitEntry.InvisibleChar = '•';
            this.table2.Add(this.limitEntry);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.limitEntry]));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.placedSince = new Gtk.CheckButton();
            this.placedSince.CanFocus = true;
            this.placedSince.Name = "placedSince";
            this.placedSince.Label = Mono.Unix.Catalog.GetString("Placed After:");
            this.placedSince.DrawIndicator = true;
            this.placedSince.UseUnderline = true;
            this.table2.Add(this.placedSince);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.placedSince]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
