// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ocmgtk {
    
    
    public partial class GenericGPSWidget {
        
        private Gtk.VBox vbox3;
        
        private Gtk.HBox hbox3;
        
        private Gtk.CheckButton limitCheck;
        
        private Gtk.Entry limitEntry;
        
        private Gtk.Button hotPlugButton;
        
        private Gtk.Label label4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label5;
        
        private Gtk.Entry formatEntry;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label3;
        
        private Gtk.Entry fileEntry;
        
        private Gtk.Button fileButton;
        
        private Gtk.Image image3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ocmgtk.GenericGPSWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "ocmgtk.GenericGPSWidget";
            // Container child ocmgtk.GenericGPSWidget.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = ((uint)(6));
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.limitCheck = new Gtk.CheckButton();
            this.limitCheck.CanFocus = true;
            this.limitCheck.Name = "limitCheck";
            this.limitCheck.Label = Mono.Unix.Catalog.GetString("Limit Number of Caches");
            this.limitCheck.DrawIndicator = true;
            this.limitCheck.UseUnderline = true;
            this.hbox3.Add(this.limitCheck);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.limitCheck]));
            w1.Position = 0;
            w1.Expand = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.limitEntry = new Gtk.Entry();
            this.limitEntry.Sensitive = false;
            this.limitEntry.CanFocus = true;
            this.limitEntry.Name = "limitEntry";
            this.limitEntry.Text = Mono.Unix.Catalog.GetString("1000");
            this.limitEntry.IsEditable = true;
            this.limitEntry.InvisibleChar = '•';
            this.hbox3.Add(this.limitEntry);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.limitEntry]));
            w2.Position = 1;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hotPlugButton = new Gtk.Button();
            this.hotPlugButton.CanFocus = true;
            this.hotPlugButton.Name = "hotPlugButton";
            this.hotPlugButton.Relief = ((Gtk.ReliefStyle)(2));
            // Container child hotPlugButton.Gtk.Container+ContainerChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Read the GPS Babel Documentation to choose the right values for these fields\n<span fgcolor=\"blue\">http://www.gpsbabel.org/readme.html</span>");
            this.label4.UseMarkup = true;
            this.hotPlugButton.Add(this.label4);
            this.hotPlugButton.Label = null;
            this.vbox3.Add(this.hotPlugButton);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.hotPlugButton]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Output Format:");
            this.hbox2.Add(this.label5);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.label5]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.formatEntry = new Gtk.Entry();
            this.formatEntry.CanFocus = true;
            this.formatEntry.Name = "formatEntry";
            this.formatEntry.Text = Mono.Unix.Catalog.GetString("geo");
            this.formatEntry.IsEditable = true;
            this.formatEntry.InvisibleChar = '•';
            this.hbox2.Add(this.formatEntry);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.formatEntry]));
            w7.Position = 1;
            this.vbox3.Add(this.hbox2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Output FIle:");
            this.hbox4.Add(this.label3);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox4[this.label3]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.fileEntry = new Gtk.Entry();
            this.fileEntry.CanFocus = true;
            this.fileEntry.Name = "fileEntry";
            this.fileEntry.Text = Mono.Unix.Catalog.GetString("~/caches.loc");
            this.fileEntry.IsEditable = true;
            this.fileEntry.InvisibleChar = '•';
            this.hbox4.Add(this.fileEntry);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox4[this.fileEntry]));
            w10.Position = 1;
            // Container child hbox4.Gtk.Box+BoxChild
            this.fileButton = new Gtk.Button();
            this.fileButton.CanFocus = true;
            this.fileButton.Name = "fileButton";
            // Container child fileButton.Gtk.Container+ContainerChild
            this.image3 = new Gtk.Image();
            this.image3.Name = "image3";
            this.image3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-open", Gtk.IconSize.Menu, 16);
            this.fileButton.Add(this.image3);
            this.fileButton.Label = null;
            this.hbox4.Add(this.fileButton);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox4[this.fileButton]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            this.vbox3.Add(this.hbox4);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
            w13.Position = 3;
            w13.Expand = false;
            w13.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.hotPlugButton.Clicked += new System.EventHandler(this.OnInfoClick);
            this.fileButton.Clicked += new System.EventHandler(this.OnFileClick);
        }
    }
}
